/**
 * Root Layout
 *
 * This is the top-level layout component for the entire application.
 * It loads all custom Google Fonts and applies them as CSS variables
 * so they can be referenced throughout the app via Tailwind utility classes.
 */

import type { Metadata } from "next";
import { Inter, Island_Moments, Jost, Poppins } from "next/font/google";
import "./globals.css";

// -- Font Configuration --
// Each font is assigned a CSS variable that maps to a Tailwind font-family utility.

// Inter: primary body font used across most text (font-int)
const inter = Inter({
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
  subsets: ["latin"],
});

// Jost: used for footer headings and descriptions (font-jost)
const jost = Jost({
  weight: ["400", "500", "600", "700"],
  variable: "--font-jost",
  subsets: ["latin"],
});

// Island Moments: decorative script font for the brand name / logo (font-island)
const islandMoments = Island_Moments({
  weight: "400",
  variable: "--font-island-moments",
  subsets: ["latin"],
});

// Poppins: used for footer links and copyright text (font-poppins)
const poppins = Poppins({
  weight: "400",
  variable: "--font-poppins",
  subsets: ["latin"],
});

// -- Page Metadata --
export const metadata: Metadata = {
  title: "Chuks Kitchen",
  description: "Generated by create next app",
};

/**
 * RootLayout wraps every page in the app.
 * - Sets the document language to English.
 * - Applies Inter as the primary CSS variable on <html>.
 * - Applies Jost, Island Moments, and Poppins variables on <body>.
 * - Enables Tailwind's antialiased text rendering.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`${jost.variable} ${islandMoments.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
